Tugas Day 14 Laravel CRUD ORM/tugas_day14/routes/web.php
<?php
use App\Http\Controllers\TableController;
use App\Http\Controllers\CastController;

Route::get('/table', [TableController::class, 'table']);
Route::get('/data-tables', [TableController::class, 'dataTables']);
Route::resource('cast', CastController::class);

Tugas Day 14 Laravel CRUD ORM/tugas_day14/app/Models/Cast.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Cast extends Model
{
    use HasFactory;

    protected $fillable = ['name', 'bio', 'birth_date'];
}

Tugas Day 14 Laravel CRUD ORM/tugas_day14/app/Models/User.php
<?php

namespace App\Models;

// use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array<int, string>
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * Get the attributes that should be cast.
     *
     * @return array<string, string>
     */
    protected function casts(): array
    {
        return [
            'email_verified_at' => 'datetime',
            'password' => 'hashed',
        ];
    }
}

Tugas Day 14 Laravel CRUD ORM/tugas_day14/app/Http/Controllers/CastController.php
<?php

namespace App\Http\Controllers;

use App\Models\Cast;
use Illuminate\Http\Request;

class CastController extends Controller
{
    // Menampilkan list data para pemain film
    public function index()
    {
        $casts = Cast::all();
        return view('cast.index', compact('casts'));
    }

    // Menampilkan form untuk membuat data pemain film baru
    public function create()
    {
        return view('cast.create');
    }

    // Menyimpan data baru ke tabel Cast
    public function store(Request $request)
    {
        $request->validate([
            'name' => 'required',
            'bio' => 'nullable',
            'birth_date' => 'required|date',
        ]);

        Cast::create($request->all());
        return redirect()->route('cast.index')->with('success', 'Cast created successfully.');
    }

    // Menampilkan detail data pemain film dengan id tertentu
    public function show(Cast $cast)
    {
        return view('cast.show', compact('cast'));
    }

    // Menampilkan form untuk edit pemain film dengan id tertentu
    public function edit(Cast $cast)
    {
        return view('cast.edit', compact('cast'));
    }

    // Menyimpan perubahan data pemain film (update) untuk id tertentu
    public function update(Request $request, Cast $cast)
    {
        $request->validate([
            'name' => 'required',
            'bio' => 'nullable',
            'birth_date' => 'required|date',
        ]);

        $cast->update($request->all());
        return redirect()->route('cast.index')->with('success', 'Cast updated successfully.');
    }

    // Menghapus data pemain film dengan id tertentu
    public function destroy(Cast $cast)
    {
        $cast->delete();
        return redirect()->route('cast.index')->with('success', 'Cast deleted successfully.');
    }
}

Tugas Day 14 Laravel CRUD ORM/tugas_day14/app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

abstract class Controller
{
    //
}

Tugas Day 14 Laravel CRUD ORM/tugas_day14/app/Http/Controllers/PageController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class PageController extends Controller
{
    public function table()
    {
        return view('table');
    }

    public function dataTables()
    {
        return view('data-tables');
    }
}

Tugas Day 14 Laravel CRUD ORM/tugas_day14/app/Http/Controllers/TableController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class TableController extends Controller
{
    public function table()
    {
        return view('table');
    }

    public function dataTables()
    {
        return view('data-tables');
    }
}

Tugas Day 14 Laravel CRUD ORM/tugas_day14/resources/views/cast/create.blade.php
@extends('layouts.master')

@section('title', 'Create Cast')

@section('content')
<div class="container mt-5">
    <div class="row">
        <div class="col-md-8 offset-md-2">
            <h2 class="mb-4">Create New Cast</h2>
            <form action="{{ route('cast.store') }}" method="POST">
                @csrf
                <div class="form-group">
                    <label for="name">Name</label>
                    <input type="text" name="name" class="form-control" required>
                </div>
                <div class="form-group">
                    <label for="bio">Bio</label>
                    <textarea name="bio" class="form-control"></textarea>
                </div>
                <div class="form-group">
                    <label for="birth_date">Birth Date</label>
                    <input type="date" name="birth_date" class="form-control" required>
                </div>
                <button type="submit" class="btn btn-primary">Submit</button>
            </form>
        </div>
    </div>
</div>
@endsection

Tugas Day 14 Laravel CRUD ORM/tugas_day14/resources/views/cast/edit.blade.php
@extends('layouts.master')

@section('title', 'Edit Cast')

@section('content')
<div class="container mt-5">
    <div class="row">
        <div class="col-md-8 offset-md-2">
            <h2 class="mb-4">Edit Cast</h2>
            <form action="{{ route('cast.update', $cast->id) }}" method="POST">
                @csrf
                @method('PUT')
                <div class="form-group">
                    <label for="name">Name</label>
                    <input type="text" name="name" class="form-control" value="{{ $cast->name }}" required>
                </div>
                <div class="form-group">
                    <label for="bio">Bio</label>
                    <textarea name="bio" class="form-control">{{ $cast->bio }}</textarea>
                </div>
                <div class="form-group">
                    <label for="birth_date">Birth Date</label>
                    <input type="date" name="birth_date" class="form-control" value="{{ $cast->birth_date }}" required>
                </div>
                <button type="submit" class="btn btn-primary">Update</button>
            </form>
        </div>
    </div>
</div>
@endsection

Tugas Day 14 Laravel CRUD ORM/tugas_day14/resources/views/cast/index.blade.php
@extends('layouts.master')

@section('title', 'Casts')

@section('content')
<div class="container mt-5">
    <div class="row">
        <div class="col-md-12">
            <h2 class="mb-4">Casts List</h2>
            <a href="{{ route('cast.create') }}" class="btn btn-success mb-3">Add New Cast</a>
            <table class="table table-bordered">
                <thead>
                    <tr>
                        <th>No</th>
                        <th>Name</th>
                        <th>Bio</th>
                        <th>Birth Date</th>
                        <th>Actions</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach ($casts as $cast)
                    <tr>
                        <td>{{ $loop->iteration }}</td>
                        <td>{{ $cast->name }}</td>
                        <td>{{ $cast->bio }}</td>
                        <td>{{ $cast->birth_date }}</td>
                        <td>
                            <a href="{{ route('cast.show', $cast->id) }}" class="btn btn-info">Show</a>
                            <a href="{{ route('cast.edit', $cast->id) }}" class="btn btn-warning">Edit</a>
                            <form action="{{ route('cast.destroy', $cast->id) }}" method="POST" style="display:inline-block;">
                                @csrf
                                @method('DELETE')
                                <button type="submit" class="btn btn-danger">Delete</button>
                            </form>
                        </td>
                    </tr>
                    @endforeach
                </tbody>
            </table>
        </div>
    </div>
</div>
@endsection

Tugas Day 14 Laravel CRUD ORM/tugas_day14/resources/views/cast/show.blade.php
@extends('layouts.master')

@section('title', 'Show Cast')

@section('content')
<div class="container mt-5">
    <div class="row">
        <div class="col-md-8 offset-md-2">
            <h2 class="mb-4">Cast Details</h2>
            <div class="card">
                <div class="card-header">
                    <h3>{{ $cast->name }}</h3>
                </div>
                <div class="card-body">
                    <p><strong>Bio:</strong> {{ $cast->bio }}</p>
                    <p><strong>Birth Date:</strong> {{ $cast->birth_date }}</p>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

Tugas Day 14 Laravel CRUD ORM/tugas_day14/resources/views/data-tables.blade.php
@extends('layouts.master')

@section('title', 'DataTables')

@section('custom_css')
<link rel="stylesheet" href="https://cdn.datatables.net/v/bs4/dt-1.11.3/datatables.min.css"/>
@endsection

@section('content')
<section class="content">
    <div class="container-fluid">
        <div class="row">
            <div class="col-12">
                <div class="card">
                    <div class="card-header">
                        <h3 class="card-title">DataTable with default features</h3>
                    </div>
                    <div class="card-body">
                        <table id="example1" class="table table-bordered table-striped">
                            <thead>
                                <tr>
                                    <th>Name</th>
                                    <th>Position</th>
                                    <th>Office</th>
                                    <th>Age</th>
                                    <th>Start date</th>
                                    <th>Salary</th>
                                </tr>
                            </thead>
                            <tbody>
                                <tr>
                                    <td>Tiger Nixon</td>
                                    <td>System Architect</td>
                                    <td>Edinburgh</td>
                                    <td>61</td>
                                    <td>2011/04/25</td>
                                    <td>$320,800</td>
                                </tr>
                                <tr>
                                    <td>Garrett Winters</td>
                                    <td>Accountant</td>
                                    <td>Tokyo</td>
                                    <td>63</td>
                                    <td>2011/07/25</td>
                                    <td>$170,750</td>
                                </tr>
                                <!-- Add more rows as needed -->
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
@endsection

@section('custom_js')
<script src="https://cdn.datatables.net/v/bs4/dt-1.11.3/datatables.min.js"></script>
<script>
    $(document).ready(function() {
        $('#example1').DataTable();
    });
</script>
@endsection

Tugas Day 14 Laravel CRUD ORM/tugas_day14/resources/views/layouts/footer.blade.php
<footer class="main-footer">
    <div class="float-right d-none d-sm-block">
        <b>Version</b> 3.2.0
    </div>
    <strong>AdminLTE Integration with Laravel.</strong>
</footer>

Tugas Day 14 Laravel CRUD ORM/tugas_day14/resources/views/layouts/master.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@yield('title')</title>
    <!-- CSS AdminLTE -->
    <link rel="stylesheet" href="{{ asset('adminlte/plugins/fontawesome-free/css/all.min.css') }}">
    <link rel="stylesheet" href="{{ asset('adminlte/dist/css/adminlte.min.css') }}">
    @yield('custom_css')
</head>
<body class="hold-transition sidebar-mini">
    <div class="wrapper">
        <!-- Navbar -->
        @include('layouts.navbar')
        <!-- Sidebar -->
        @include('layouts.sidebar')
        <!-- Content Wrapper -->
        <div class="content-wrapper">
            @yield('content')
        </div>
        <!-- Footer -->
        @include('layouts.footer')
    </div>
    <!-- JS AdminLTE -->
    <script src="{{ asset('adminlte/plugins/jquery/jquery.min.js') }}"></script>
    <script src="{{ asset('adminlte/plugins/bootstrap/js/bootstrap.bundle.min.js') }}"></script>
    <script src="{{ asset('adminlte/dist/js/adminlte.min.js') }}"></script>
    @yield('custom_js')
</body>
</html>

Tugas Day 14 Laravel CRUD ORM/tugas_day14/resources/views/layouts/navbar.blade.php
<nav class="main-header navbar navbar-expand navbar-white navbar-light">
    <!-- Left navbar links -->
    <ul class="navbar-nav">
        <li class="nav-item">
            <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
        </li>
    </ul>
</nav>

Tugas Day 14 Laravel CRUD ORM/tugas_day14/resources/views/layouts/sidebar.blade.php
<aside class="main-sidebar sidebar-dark-primary elevation-4">
    <!-- Brand Logo -->
    <a href="#" class="brand-link">
        <span class="brand-text font-weight-light">AdminLTE</span>
    </a>
    <!-- Sidebar -->
    <div class="sidebar">
        <!-- Sidebar Menu -->
        <nav class="mt-2">
            <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
                <li class="nav-item">
                    <a href="{{ url('/table') }}" class="nav-link">
                        <i class="nav-icon fas fa-table"></i>
                        <p>Table</p>
                    </a>
                </li>
                <li class="nav-item">
                    <a href="{{ url('/data-tables') }}" class="nav-link">
                        <i class="nav-icon fas fa-database"></i>
                        <p>Data Tables</p>
                    </a>
                </li>
            </ul>
        </nav>
    </div>
</aside>

Tugas Day 14 Laravel CRUD ORM/tugas_day14/resources/views/table.blade.php
@extends('layouts.master')

@section('title', 'Table')

@section('content')
<section class="content">
    <div class="container-fluid">
        <div class="row">
            <div class="col-12">
                <div class="card">
                    <div class="card-header">
                        <h3 class="card-title">Task Table</h3>
                    </div>
                    <div class="card-body">
                        <table class="table table-bordered">
                            <thead>
                                <tr>
                                    <th style="width: 10px">#</th>
                                    <th>Task</th>
                                    <th>Progress</th>
                                    <th style="width: 40px">Label</th>
                                </tr>
                            </thead>
                            <tbody>
                                <tr>
                                    <td>1.</td>
                                    <td>Update software</td>
                                    <td>
                                        <div class="progress progress-xs">
                                            <div class="progress-bar progress-bar-danger" style="width: 55%"></div>
                                        </div>
                                    </td>
                                    <td><span class="badge bg-danger">55%</span></td>
                                </tr>
                                <tr>
                                    <td>2.</td>
                                    <td>Clean database</td>
                                    <td>
                                        <div class="progress progress-xs">
                                            <div class="progress-bar bg-warning" style="width: 70%"></div>
                                        </div>
                                    </td>
                                    <td><span class="badge bg-warning">70%</span></td>
                                </tr>
                                <tr>
                                    <td>3.</td>
                                    <td>Cron job running</td>
                                    <td>
                                        <div class="progress progress-xs progress-striped active">
                                            <div class="progress-bar bg-primary" style="width: 30%"></div>
                                        </div>
                                    </td>
                                    <td><span class="badge bg-primary">30%</span></td>
                                </tr>
                                <tr>
                                    <td>4.</td>
                                    <td>Fix and squish bugs</td>
                                    <td>
                                        <div class="progress progress-xs progress-striped active">
                                            <div class="progress-bar bg-success" style="width: 90%"></div>
                                        </div>
                                    </td>
                                    <td><span class="badge bg-success">90%</span></td>
                                </tr>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
@endsection